//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneHundredAndEightyCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneHundredAndEightyCore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v. 2.2.
        /// </summary>
        public static string AboutTabVersion {
            get {
                return ResourceManager.GetString("AboutTabVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam 1 enabled.
        /// </summary>
        public static string Cam1EnabledCheckBoxText {
            get {
                return ResourceManager.GetString("Cam1EnabledCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam1.
        /// </summary>
        public static string Cam1SettingsTabName {
            get {
                return ResourceManager.GetString("Cam1SettingsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam 2 enabled.
        /// </summary>
        public static string Cam2EnabledCheckBoxText {
            get {
                return ResourceManager.GetString("Cam2EnabledCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam2.
        /// </summary>
        public static string Cam2SettingsTabName {
            get {
                return ResourceManager.GetString("Cam2SettingsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam 3 enabled.
        /// </summary>
        public static string Cam3EnabledCheckBoxText {
            get {
                return ResourceManager.GetString("Cam3EnabledCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam3.
        /// </summary>
        public static string Cam3SettingsTabName {
            get {
                return ResourceManager.GetString("Cam3SettingsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam 4 enabled.
        /// </summary>
        public static string Cam4EnabledCheckBoxText {
            get {
                return ResourceManager.GetString("Cam4EnabledCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam4.
        /// </summary>
        public static string Cam4SettingsTabName {
            get {
                return ResourceManager.GetString("Cam4SettingsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable camera.
        /// </summary>
        public static string CamCheckBoxHelperText {
            get {
                return ResourceManager.GetString("CamCheckBoxHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras horizontal field of view.
        /// </summary>
        public static string CamFovHelperText {
            get {
                return ResourceManager.GetString("CamFovHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras HFOV.
        /// </summary>
        public static string CamFovLabelText {
            get {
                return ResourceManager.GetString("CamFovLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Id. Use CamCalibrator to find it.
        /// </summary>
        public static string CamIdHelperText {
            get {
                return ResourceManager.GetString("CamIdHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam vertical resolution. For now 720 max available.
        /// </summary>
        public static string CamResHHelperText {
            get {
                return ResourceManager.GetString("CamResHHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam resolution height.
        /// </summary>
        public static string CamResHLabelText {
            get {
                return ResourceManager.GetString("CamResHLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam horizontal resolution. For now 1280 max available.
        /// </summary>
        public static string CamResWHelperText {
            get {
                return ResourceManager.GetString("CamResWHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam resolution width.
        /// </summary>
        public static string CamResWLabelText {
            get {
                return ResourceManager.GetString("CamResWLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line from bull to sector, where cam is setup.
        /// </summary>
        public static string CamSetupSectorHelperText {
            get {
                return ResourceManager.GetString("CamSetupSectorHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera X.Setup point on projection image. Use &apos;Calibrate&apos; button.
        /// </summary>
        public static string CamXSetupPointHelperText {
            get {
                return ResourceManager.GetString("CamXSetupPointHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Y.Setup point on projection image. Use &apos;Calibrate&apos; button.
        /// </summary>
        public static string CamYSetupPointHelperText {
            get {
                return ResourceManager.GetString("CamYSetupPointHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose player avatar image.
        /// </summary>
        public static string ChoosePlayerAvatarText {
            get {
                return ResourceManager.GetString("ChoosePlayerAvatarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no &apos;{0}&apos; in root folder.
        /// </summary>
        public static string DbNotExistsErrorText {
            get {
                return ResourceManager.GetString("DbNotExistsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EmptyUserIcon {
            get {
                object obj = ResourceManager.GetObject("EmptyUserIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error DB migrating from [{0}] to [{1}]
        ///Please, contact developer.
        /// </summary>
        public static string ErrorDbMigrationText {
            get {
                return ResourceManager.GetString("ErrorDbMigrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction sleep time.
        /// </summary>
        public static string ExtractionSleepTimeLabelText {
            get {
                return ResourceManager.GetString("ExtractionSleepTimeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold sleep time in seconds for darts extraction from dartboard process. Default value is &apos;4&apos;.
        /// </summary>
        public static string ExtrectionSleepTimeHelperText {
            get {
                return ResourceManager.GetString("ExtrectionSleepTimeHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralSettingsTabName {
            get {
                return ResourceManager.GetString("GeneralSettingsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon2 {
            get {
                object obj = ResourceManager.GetObject("icon2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string MainSettingsTabName {
            get {
                return ResourceManager.GetString("MainSettingsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal dart contour arc on image to be detected. Default value is &apos;105&apos;.
        /// </summary>
        public static string MinContourArcHelperText {
            get {
                return ResourceManager.GetString("MinContourArcHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal contour arc.
        /// </summary>
        public static string MinContourArcLabelText {
            get {
                return ResourceManager.GetString("MinContourArcLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of moves, indicating that another throw is done. Default value is &apos;600&apos;.
        /// </summary>
        public static string MovesDartHelperText {
            get {
                return ResourceManager.GetString("MovesDartHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves dart value.
        /// </summary>
        public static string MovesDartLabelText {
            get {
                return ResourceManager.GetString("MovesDartLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After move detected threshold sleep time in seconds. Default value is &apos;0.25&apos;.
        /// </summary>
        public static string MovesDetectedHelperText {
            get {
                return ResourceManager.GetString("MovesDetectedHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move detected sleep time.
        /// </summary>
        public static string MovesDetectedLabelText {
            get {
                return ResourceManager.GetString("MovesDetectedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of moves, indicating that you extract darts from dartboard after throws. Default value is &apos;8000&apos;.
        /// </summary>
        public static string MovesExtractionHelperText {
            get {
                return ResourceManager.GetString("MovesExtractionHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves extraction value.
        /// </summary>
        public static string MovesExtractionLabelText {
            get {
                return ResourceManager.GetString("MovesExtractionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of noise moves. Default value is &apos;150&apos;.
        /// </summary>
        public static string MovesNoiseHelperText {
            get {
                return ResourceManager.GetString("MovesNoiseHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves noise value.
        /// </summary>
        public static string MovesNoiseLabelText {
            get {
                return ResourceManager.GetString("MovesNoiseLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points for classic game type can&apos;t be &apos;Free&apos;.
        /// </summary>
        public static string NewClassicGamePointsNotSelectedErrorText {
            get {
                return ResourceManager.GetString("NewClassicGamePointsNotSelectedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players not selected.
        /// </summary>
        public static string NewGamePlayersNotSelectedErrorText {
            get {
                return ResourceManager.GetString("NewGamePlayersNotSelectedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New player name and nickname must be filled in....
        /// </summary>
        public static string NewPlayerEmptyDataErrorText {
            get {
                return ResourceManager.GetString("NewPlayerEmptyDataErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined the club!.
        /// </summary>
        public static string NewPlayerSuccessfullySavedText {
            get {
                return ResourceManager.GetString("NewPlayerSuccessfullySavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality not implemented yet. Coming soon....
        /// </summary>
        public static string NotImplementedYetErrorText {
            get {
                return ResourceManager.GetString("NotImplementedYetErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar image can not be more that 512x512 px..
        /// </summary>
        public static string PlayerAvatarTooBigErrorText {
            get {
                return ResourceManager.GetString("PlayerAvatarTooBigErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian smooth of ROI image. Default value is &apos;5&apos;.
        /// </summary>
        public static string SmoothGausHelperText {
            get {
                return ResourceManager.GetString("SmoothGausHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth gaussian value.
        /// </summary>
        public static string SmoothGausLabelText {
            get {
                return ResourceManager.GetString("SmoothGausLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Start_logo4 {
            get {
                object obj = ResourceManager.GetObject("Start_logo4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Successfully migrated from [{0}] to [{1}].
        /// </summary>
        public static string SuccessDbMigrationText {
            get {
                return ResourceManager.GetString("SuccessDbMigrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold sleep time between cams work in seconds. Default value is &apos;0.125&apos;.
        /// </summary>
        public static string ThresholdSleepTimeHelperText {
            get {
                return ResourceManager.GetString("ThresholdSleepTimeHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold sleep time.
        /// </summary>
        public static string ThresholdSleepTimeLabelText {
            get {
                return ResourceManager.GetString("ThresholdSleepTimeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from camera to bull in cm.
        /// </summary>
        public static string ToCamHelperText {
            get {
                return ResourceManager.GetString("ToCamHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] version App can&apos;t work with [{1}] version DB.
        /// </summary>
        public static string VersionsMismatchErrorText {
            get {
                return ResourceManager.GetString("VersionsMismatchErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB version [{0}] and App version [{1}] mistmatch. 
        ///Would you like to migrate your DB to version {1} ?.
        /// </summary>
        public static string VersionsMismatchWarningQuestionText {
            get {
                return ResourceManager.GetString("VersionsMismatchWarningQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection enabled.
        /// </summary>
        public static string WithDetectionCheckBoxText {
            get {
                return ResourceManager.GetString("WithDetectionCheckBoxText", resourceCulture);
            }
        }
    }
}
