namespace OneHundredAndEightyCore.Common
{
    public enum Column
    {
        Value,
        Name,
        Id,
        NickName,
        RegistrationTimestamp,
        Statistic,
        Achieves,
        StartTimestamp,
        EndTimestamp,
        Type,
        Player,
        GameResult,
        Points,
        Game,
        Sector,
        Result,
        Number,
        PoiX,
        PoiY,
        ProjectionResolution,
        Timestamp,
        Avatar,
        Throw1,
        Throw2,
        Throw3,
        LegsPlayed,
        LegsWon
    }
}