namespace OneHundredAndEightyCore.Enums
{
    public enum Column
    {
        Value,
        Name,
        Id,
        NickName,
        RegistrationDateTime,
        StatisticId,
        StartDateTime,
        EndDateTime,
        ThrowTypeId,
        PlayerId,
        GameResultTypeId,
        Points,
        GameId,
        Sector,
        ThrowResultId,
        Number,
        PoiX,
        PoiY,
        ProjectionResolution,
        DateTime,
        Avatar,
        Throw1Id,
        Throw2Id,
        Throw3Id,
        LegsPlayed,
        SetsPlayed,
        LegsWon,
        SetsWon,
        AchieveId,
        ObtainedDateTime
    }
}