namespace OneHundredAndEightyCore.Enums
{
    public enum Column
    {
        Value,
        Name,
        Id,
        NickName,
        RegistrationTimestamp,
        Statistic,
        StartTimestamp,
        EndTimestamp,
        Type,
        Player,
        GameResult,
        Points,
        Game,
        Sector,
        Result,
        Number,
        PoiX,
        PoiY,
        ProjectionResolution,
        Timestamp,
        Avatar,
        Throw1,
        Throw2,
        Throw3,
        LegsPlayed,
        SetsPlayed,
        LegsWon,
        SetsWon,
        AchieveId,
        PlayerId
    }
}